services:
  chroma:
    image: chromadb/chroma
    ports:
      - "8001:8000"
    volumes:
      - ./chroma_data:/chroma/.chroma/index
    # CORREÇÃO FINAL: Comando simplificado para a nova versão do ChromaDB
    command: "run --host 0.0.0.0 --port 8000"