# docker-compose.yml
# Arquivo atualizado para incluir os serviços de PostgreSQL e Redis, além do ChromaDB.

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: pronasys_user
      POSTGRES_PASSWORD: pronasys_password
      POSTGRES_DB: pronasys_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  chroma:
    image: chromadb/chroma
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma

volumes:
  postgres_data:
  redis_data:
  chroma_data:

